### ISSUE TITLE
change 'name' to 'type' and 'instance'

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#171]
Note: this change cannot be made until instance and type are consistently populated by Lowell into neo4j.  Cypher queries with *.name will need to be converted to use *.instance and *.type instance.

1.  Wherever there is a box to search for neuron name, it should actually be a search for 'type or instance name' (custom cypher queries that use name and neuprint http will have to make a small change as well)
2.  Wherever there is a 'name' column for a plugin, there should be 'type' and 'instance' columns instead.

This update is tricky insofar are there are multiple dependencies.  I think we do the following.

1.  Update neuprint to populate instance, type, and name fields.
2.  Modify neuprint http to use either instance, type, or name (and return all 3 of them) (neuprinthttp should be modified to handle any of these fields)
3.  Modify neuprint explorer custom cypher and form fields and columns to just use instance and type (and not name)
4.  Eventually modify neuprint http and the main neuprint model to get rid of the old .name field

**Comment by neomorphic** [comment]
It looks like instance is only available for the hemibrain data set. Is there a plan to go back and add it to the mb6 and fib25 datasets?

**Comment by neomorphic** [comment]
Largely completed in the name_to_instance_type branch. Fixed in commits 
connectome-neuprint/neuPrintExplorerPlugins@ed4aba2469, 
connectome-neuprint/neuPrintExplorerPlugins@ea63fabaa1, 
connectome-neuprint/neuPrintExplorerPlugins@a13d81ca5, 
connectome-neuprint/neuPrintExplorerPlugins@5a1506e082, 
connectome-neuprint/neuPrintExplorerPlugins@cfc672b00f, 
connectome-neuprint/neuPrintExplorerPlugins@674da4026d, 
connectome-neuprint/neuPrintExplorerPlugins@8579a531ec7e, 
connectome-neuprint/neuPrintExplorerPlugins@e1d1f6b3cc8,
 connectome-neuprint/neuPrintExplorerPlugins@43457e48cf0, 
connectome-neuprint/neuPrintExplorerPlugins@efc2d673
