### ISSUE TITLE
Add ability to see the old queries when scrolling through old results tabs 

### ISSUE THREAD

**Issue by emjoyce** [connectome-neuprint/neuPrintExplorer#175]
When you move between tabs to see results of older custom and built in queries, it would be good to be able to see the query itself as well.

**Comment by neomorphic** [comment]
@emjoyce , can you clarify this for me a little? There is already a way to see the query with the 'i' icon in the top bar of the results tab. Would you like to see the query at the top of the results, without having to click on that icon?

**Comment by emjoyce** [comment]
@neomorphic I initially meant that the custom query would pop back up into the text box on the left side of the page or the built in query and it's inputs show back up, but I did not know that the i icon worked for old custom queries as well. It could still be nice to have the displayed query change to reflect the results being viewed, but I can pass this info around to the connectome annotation team members that use neuprint

**Comment by neomorphic** [comment]
@emjoyce, putting the old query into the text box on the left has a few implications.

1. What if they have written a new query and are looking back at the old tab to get an input value, should we destroy that query?
2. What if the user is writing a query on different plugin, do we throw that out and load in the custom plugin?

I think a better solution is to make the 'i' icon more obvious. When clicked it should show the query above the results table and remain opened, until the 'i' icon is clicked again. This way you will be able to see the query immediately. We could also add a copy to clipboard option so that you can quickly copy the query and paste it into the custom query form.

**Comment by emjoyce** [comment]
@neomorphic Yes I think your solution would work well.

**Comment by neomorphic** [comment]
Fixed in 682c45fdbaa2 && 715647fb666. The i icon now opens the cypher query in the currently selected tab. The query remains visible until the close or 'i' icon is pressed. Clicking on the cypher text will copy it to the clipboard, so that it can be pasted into the custom query text input. This should be available in release 1.12.0
