### ISSUE TITLE
URL-based integration API

### ISSUE THREAD

**Issue by krokicki** [connectome-neuprint/neuPrintExplorer#188]
It would be nice if there was a simple and long-term URL-based API for linking directly to a body. For example http://host:port/datasets/hemibrain/skeleton/1038964771 could redirect to a view with all relevant information about that skeleton. For example, currently it might redirect to the view with both the "Find Neuron" and "Skeleton" tabs:

https://emdata1.int.janelia.org:11000/results?dataset=hemibrain&q=1&qt=findneurons&qr%5B0%5D%5Bcode%5D=sk&qr%5B0%5D%5Bds%5D=hemibrain&qr%5B0%5D%5Bpm%5D%5BdataSet%5D=hemibrain&qr%5B0%5D%5Bpm%5D%5Bskip%5D=true&qr%5B0%5D%5Bpm%5D%5BbodyIds%5D=1038964771&qr%5B0%5D%5Bpm%5D%5Bcoordinates%5D=19702.782300788163%2C21302.07916593369%2C56568.95976278046%2C19702.78230078816%2C21302.079165933697%2C15256.658987806328&qr%5B1%5D%5Bcode%5D=fn&qr%5B1%5D%5Bds%5D=hemibrain&qr%5B1%5D%5Bpm%5D%5Bdataset%5D=hemibrain&qr%5B1%5D%5Bpm%5D%5Ball_segments%5D=false&qr%5B1%5D%5Bpm%5D%5Bneuron_id%5D=1038964771&qr%5B1%5D%5BvisProps%5D%5BrowsPerPage%5D=25&tab=1

If new views are added in the future, or this view API changes, this could be updated, and the integrated applications would be isolated from any changes.

**Comment by stephenplaza** [comment]
This is more of a neuprint http issue since that defines the REST api.  Incidentally, because skeletons are mostly treated as a blob type this is was scheduled to be added by next week.   You can do a custom query to get a skeleton now if you want.  It just requires passing the proper cypher query to the REST api.

**Comment by krokicki** [comment]
Thanks, that's good to know. To clarify, I'm trying to link to Neuprint from another application, for integration purposes. An analogy would be the way YouTube links to videos: https://www.youtube.com/watch?v=<videoid> 

I know that I can do this currently with a cypher query, but the resulting URL's are very long, and not easy to pass around, and the implementation details are subject to change, which doesn't make it a good way to create external references.

**Comment by stephenplaza** [comment]
yes, as mentioned, I will be extending the REST API shortly to augment the custom cypher.  For something as simple as skeleton this makes sense.  But for some of our other requests, it is actually quite hard to define a connectomics API since everyone is using the tool differently.  The most common queries we will try to make a generic endpoint.

**Comment by neomorphic** [comment]
Fixed in 3dc1bcb36634e4b689876823a1430f8ba7ddf978, should be ready for release in v 1.13.0 of the site
