### ISSUE TITLE
add option to collapse connections by cell type

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#191]
For the simple connectivity widget, the user should be able to click a button that allows the connectivity table to collapse all common cell types.  In other words, all the neurons of the same type should be combined into a super node.

**Comment by neomorphic** [comment]
There are a lot of instances that have a type of 'null'. Should those be combined together?

**Comment by neomorphic** [comment]
@stephenplaza if we collapse the rows by cell type, there are a number of columns that will break.
1. id -> this will be irrelevant, since there could be hundreds in this column per row.
2. status -> this could be mixed
3. instance -> there will be multiple
4. #pre -> the links will have to be changed as they currently run a query against a single body id
5. #post -> the links will have to be changed as they currently run a query against a single body id

4 & 5 can be done since we have the option to query simple connections by type, instance or bodyId. 1 -> 3 seem a little troublesome, with the easiest option being to hide them.

**Comment by neomorphic** [comment]
Completed in 63297f00b46
