### ISSUE TITLE
Find Neurons built in query will not return name.* for partial names inside of parentheses 

### ISSUE THREAD

**Issue by emjoyce** [connectome-neuprint/neuPrintExplorer#195]
When you search for neurons like DNp13(pMN1)_L by searching pMN1.* in Find Neurons, no results are returned. The same holds true for other partial neuron names in parentheses, such as (ABDL)_L neurons.

In custom queries, `WHERE n.name CONTAINS "ABDL"` returns the desired results whereas `WHERE n.name =~"ABDL.*"` does not, so the fix may be as simple as changing the query underlying Find Neurons from `neuron.name =~""` to `neuron.name CONTAINS "".`

**Comment by neomorphic** [comment]
This bug is a feature. The idea is to allow a regular expression in the neuron input. In order for it to work correctly, certain characters need to be escaped correctly. In the example above, the queries would need to be changed to '.* pMN1.*' and '.*ABDL.*' respectively. For more specific searches you could try: 'DNp13\\(pMN1\\)_L' or 'DNp13\\(pMN1\\).*' I have added an additional warning text about regular expressions, whenever someone adds a ')' to the query as can be seen in the attached image. This should hopefully reduce the confusion around this input. It will be made available in the next release.

![regex_warning](https://user-images.githubusercontent.com/10181/64201227-2b489180-ce5c-11e9-95c1-9bfc153a40cb.png)
