### ISSUE TITLE
Add edit flag to each users profile. - Affects neuroglancer

### ISSUE THREAD

**Issue by neomorphic** [connectome-neuprint/neuPrintExplorer#274]
This edit flag will be an option that the user can turn on from their profile page. Once turned on they will receive neuroglancer data from our servers. If turned off, the default, they will get neuroglancer data from google buckets.

**Comment by neomorphic** [comment]
@stephenplaza does this description match what you want to have?

**Comment by neomorphic** [comment]
Also need to pass a setting to react-neuroglancer so it know which collection of data it should be displaying.

**Comment by stephenplaza** [comment]
And to clarify, my thought was that in the neuroglancer meta json stored in neuprint, that we would just add a flag to each potential data source like 'advanced' for advanced mode.  If there is no advanced mode, the layer is always passed.  If advanced is true or false it is only shown depending on the advanced setting.

This can be done early / mid next week since we can at least test google pre-computed without any toggle for now.

**Comment by neomorphic** [comment]
This won't be done as we have moved everything to precomputed layers.
